Lf: 5
batch_size: 70
beta1: 0.5
beta2: 0.999
checkpoint_dir: result_MultiGraphGAN/models/
cls_loss: BCE
d_lr: 0.0001
dropout: 0.5
g_lr: 0.0001
hidden1: 32
hidden2: 16
in_feature: 595
lambda_cls: 1
lambda_idt: 10
lambda_info: 1
lambda_rec: 0.01
lambda_reg: 0.1
lambda_topology: 0.1
log_dir: result_MultiGraphGAN/logs/
log_step: 5
mode: train
model_save_step: 10
n_critic: 5
nb_clusters: 2
num_domains: 6
num_iters: 10
num_workers: 1
result_dir: result_MultiGraphGAN/results/
result_root: result_MultiGraphGAN/
resume_iters: null
sample_dir: result_MultiGraphGAN/samples/
sample_step: 5
test_iters: 10
